### PR TITLE
Swap endianness of data rows

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Uses GCC's `__builtin_bswap32`, which should map to ARM's `REV` instruction

### CODE REVIEW

**Comment by ps2** [comment]
Would it make sense to have a romManager.addRow(unsigned int row) method? that would encapsulate several things that are being repeated in shoe_rom.cpp (accessing table.data, config.rowCounter, incrementing rowCounter, and byte swapping)

**Comment by ps2** [comment]
clever use of asm tricks, too. 👍

**Comment by GeorgeHahn** [comment]
Absolutely. I'm about to head over to Lab651; I'll refactor that in as soon
as I arrive.

**Comment by GeorgeHahn** [comment]
Closes #5

**Comment by ps2** [comment]
Very nice!

**Pull request merged**
